# Métodos iterativos

Vicente Helano  
UFCA | Centro de Ciências e Tecnologia

# Método de Jacobi

Considere o sistema:

\begin{array}{rcrcrcr}
9x_1 &+& x_2 &+& x_3 &=& 1\\
2x_1 &+& 10x_2 &+& 3x_3 &=& 2\\
3x_1 &+& 4x_2 &+& 11x_3 &=& 3
\end{array}

# Método de Jacobi

Para um sistema $n \times n$, teremos:

\begin{align*}
x_1^{(k+1)} &= \frac{1}{a_{11}} \left( -a_{12}x_2^{(k)} -  a_{13}x_3^{(k)} - \cdots - a_{1n}x_n^{(k)} + b_1 \right)\\
x_2^{(k+1)} &= \frac{1}{a_{22}} \left( -a_{21}x_1^{(k)} -  a_{23}x_3^{(k)} - \cdots - a_{2n}x_n^{(k)} + b_2 \right)\\
&\vdots\\
x_n^{(k+1)} &= \frac{1}{a_{nn}} \left( -a_{n1}x_1^{(k)} -  a_{n2}x_2^{(k)} - \cdots - a_{n,(n-1)}x_{n-1}^{(k)} + b_n \right)\\
\end{align*}

$$
x_i^{(k+1)} = \frac{1}{a_{ii}}\left[b_i \displaystyle -\sum_{\substack{j=1 \\ j\ne i}}^{n} \left( a_{ij}x_j^{(k)} \right)    \right] \qquad i = 1, 2, \dotsc n
$$

## Critério de parada

$$
\|\mathbf{x}^{(k+1)} - \mathbf{x}^{(k)} \| < \varepsilon \cdot \max\left\{\|\mathbf{x}^{(k+1)}\|, 1\right\}
$$

Usaremos a `linalg.norm` por conveniência. Por exemplo,

In [2]:
import numpy as np
from numpy import linalg as la

tol = 1e-6
x0 = np.array([[1],[2],[3]])
x = np.array([[4],[5],[6]])

la.norm(x-x0) < tol*max([la.norm(x),1.0])

False

## Implementação

In [3]:
def jacobi(A,b,x0,N,tol):
    m,n = A.shape
    x = np.zeros((n,1))
    k = 1
    while (k <= N):
        for i in range(n):
            soma = b[i]
            for j in range(n):
                if (i != j):
                    soma = soma - A[i,j]*x0[j]
            x[i] = soma/A[i,i]
            
        if la.norm(x-x0) < tol*max([la.norm(x),1]):
            return x,k
        
        k = k + 1
        for i in range(n):
            x0[i] = x[i]
    
    print("Número máximo de iterações foi excedido")
    return x,k

Quantos flops realiza o método de Jacobi?

## Exemplo

\begin{array}{rcrcrcr}
9x_1 &+& x_2 &+& x_3 &=& 1\\
2x_1 &+& 10x_2 &+& 3x_3 &=& 2\\
3x_1 &+& 4x_2 &+& 11x_3 &=& 3
\end{array}

In [17]:
# Teste de Jacobi
A = np.array([[9.0,  1.0,  1.0],
              [2.0, 10.0,  3.0],
              [3.0,  4.0, 11.0]])
b = np.array([[1.0],[2.0],[3.0]])
x0 = np.zeros(b.shape)
print(x0)
jacobi(A,b,x0,100,1e-8)


[[0.]
 [0.]
 [0.]]


(array([[0.07438017],
        [0.12278631],
        [0.20779221]]),
 23)

## Método de Gauss-Seidel

\begin{align*}
x_1^{(k+1)} &= \frac{1}{a_{11}} \left( -a_{12}x_2^{(k)} -  a_{13}x_3^{(k)} - \cdots - a_{1n}x_n^{(k)} + b_1 \right)\\
x_2^{(k+1)} &= \frac{1}{a_{22}} \left( -a_{21}x_1^{\color{red}{\bf (k+1)}} -  a_{23}x_3^{(k)} - \cdots - a_{2n}x_n^{(k)} + b_2 \right)\\
&\vdots\\
x_n^{(k+1)} &= \frac{1}{a_{nn}} \left( -a_{n1}x_1^{\color{red}{\bf (k+1)}} -  a_{n2}x_2^{\color{red}{\bf (k+1)}} - \cdots - a_{n,(n-1)}x_{n-1}^{\color{red}{\bf (k+1)}} + b_n \right)\\
\end{align*}

$$
x_i^{(k+1)} = \frac{1}{a_{ii}}
\left[ b_i \displaystyle  -\sum_{\substack{j=1}}^{i-1} \left( a_{ij}x_j^{\color{red}{\bf (k+1)}} \right)
                      -\sum_{\substack{j=i+1}}^{n} \left( a_{ij}x_j^{(k)} \right)     \right] \qquad i = 1, 2, \dotsc n
$$

## Implementação

In [5]:
def gauss_seidel(A,b,x0,N,tol):
    m,n = A.shape
    x = np.zeros((n,1))
    k = 1
    while (k <= N):
        for i in range(n):
            soma = b[i]
            # contribuição de x_{k+1}
            for j in range(0,i):
                soma = soma - A[i,j]*x[j]
                
            # contribuição de x_k
            for j in range(i+1,n):
                soma = soma - A[i,j]*x0[j]
                    
            x[i] = soma/A[i,i]
            
        if la.norm(x-x0) < tol*max([la.norm(x),1]):
            return x,k
        
        k = k + 1
        for i in range(n):
            x0[i] = x[i]
    
    print("Número máximo de iterações foi excedido")
    return x,k

## Exemplo

In [6]:
# Teste de Gauss-Seidel
A = np.array([[9.0,  1.0,  1.0],
              [2.0, 10.0,  3.0],
              [3.0,  4.0, 11.0]])
b = np.array([[1.0],[2.0],[3.0]])
x0 = np.array([[0.0],[0.0],[0.0]])

gauss_seidel(A,b,x0,100,1e-8)

(array([[0.07438017],
        [0.1227863 ],
        [0.20779221]]),
 9)

# Técnica de particionamento 

Considere um sistema $\mathbf{A}\mathbf{x} = \mathbf{b}$ e escreva

$$
\mathbf{A} = \mathbf{D} + \mathbf{L} + \mathbf{U}
$$

* $\mathbf{D} = [\,a_{ii} \,]$, $i = 1, 2, \dotsc, n$
* $\mathbf{L} = [\,a_{ij} \,]$, $i,j = 1, 2, \dotsc, n$, $i > j$
* $\mathbf{U} = [\,a_{ij} \,]$, $i,j = 1, 2, \dotsc, n$, $i < j$

## Matriz de Jacobi

\begin{align*}
\mathbf{A}\mathbf{x} &= \left(\mathbf{D} + \mathbf{L} + \mathbf{U} \right) \mathbf{x} = \mathbf{b}\\
\mathbf{D}\mathbf{x} &=  -\left(\mathbf{L} + \mathbf{U} \right) \mathbf{x} + \mathbf{b}\\
\mathbf{x}^{(k+1)} &=  -\mathbf{D}^{-1}\left(\mathbf{L} + \mathbf{U} \right) \mathbf{x}^{(k)} + \mathbf{D}^{-1}\mathbf{b}\\
&= \mathbf{T}_j \mathbf{x}^{(k)} + \mathbf{c}
\end{align*}

## Matriz de Jacobi

\begin{array}{rcrcrcr}
9x_1 &+& x_2 &+& x_3 &=& 1\\
2x_1 &+& 10x_2 &+& 3x_3 &=& 2\\
3x_1 &+& 4x_2 &+& 11x_3 &=& 3
\end{array}

$$\mathbf{T}_j =
\begin{bmatrix}
0 & -\frac{1}{9}  & -\frac{1}{9}\\
-\frac{2}{10}  & 0 & -\frac{3}{10}\\
-\frac{3}{11}  & -\frac{4}{11} & 0\\
\end{bmatrix}
$$

In [7]:
A = np.array([[9.0,  1.0,  1.0],
              [2.0, 10.0,  3.0],
              [3.0,  4.0, 11.0]])
D = np.diag(np.diag(A))
L = np.tril(A,-1)
U = np.triu(A,1)
Tj = -np.dot(la.inv(D),L+U)
Tj

array([[-0.        , -0.11111111, -0.11111111],
       [-0.2       , -0.        , -0.3       ],
       [-0.27272727, -0.36363636, -0.        ]])

## Matriz de Gauss-Seidel

\begin{align*}
\mathbf{A}\mathbf{x} &= \left(\mathbf{D} + \mathbf{L} + \mathbf{U} \right) \mathbf{x} = \mathbf{b}\\
\left(\mathbf{D}+\mathbf{L}\right)\mathbf{x} &=  - \mathbf{U} \mathbf{x} + \mathbf{b}\\
\mathbf{x}^{(k+1)} &=  -\left(\mathbf{D}+\mathbf{L}\right)^{-1}\mathbf{U} \mathbf{x}^{(k)} + \left(\mathbf{D}+\mathbf{L}\right)^{-1}\mathbf{b}\\
&= \mathbf{T}_g \mathbf{x}^{(k)} + \mathbf{c}
\end{align*}

## Matriz de Gauss-Seidel

\begin{array}{rcrcrcr}
9x_1 &+& x_2 &+& x_3 &=& 1\\
2x_1 &+& 10x_2 &+& 3x_3 &=& 2\\
3x_1 &+& 4x_2 &+& 11x_3 &=& 3
\end{array}

$$\mathbf{T}_g =
\begin{bmatrix}
0 & -\frac{1}{9}  & -\frac{1}{9}\\
0  & \frac{1}{45} & -\frac{5}{18}\\
0  & \frac{1}{45} & \frac{13}{99}\\
\end{bmatrix}
$$

In [8]:
A = np.array([[9.0,  1.0,  1.0],
              [2.0, 10.0,  3.0],
              [3.0,  4.0, 11.0]])
D = np.diag(np.diag(A))
L = np.tril(A,-1)
U = np.triu(A,1)
Tg = -np.dot(la.inv(D+L),U)
Tg

array([[-0.        , -0.11111111, -0.11111111],
       [-0.        ,  0.02222222, -0.27777778],
       [-0.        ,  0.02222222,  0.13131313]])

## Critério de convergência

**Teorema**. Um método iterativo da forma

$$
\mathbf{x}^{(k+1)} = \mathbf{M} \mathbf{x}^{(k)} + \mathbf{c} \qquad k = 0, 1, \dotsc
$$

converge para qualquer valor inicial $\mathbf{x}^{(0)}$ se, e somente se,

$$
\rho(\mathbf{M}) = \max_{1 \le i \le n} |\lambda_i| < 1
$$

## Critério de convergência

\begin{array}{rcrcrcr}
9x_1 &+& x_2 &+& x_3 &=& 1\\
2x_1 &+& 10x_2 &+& 3x_3 &=& 2\\
3x_1 &+& 4x_2 &+& 11x_3 &=& 3
\end{array}

$$\mathbf{T}_j =
\begin{bmatrix}
0 & -\frac{1}{9}  & -\frac{1}{9}\\
-\frac{2}{10}  & 0 & -\frac{3}{10}\\
-\frac{3}{11}  & -\frac{4}{11} & 0\\
\end{bmatrix}
$$

In [9]:
max(abs(la.eigvals(Tj)))

0.4472271510919682

## Critério de convergência

\begin{array}{rcrcrcr}
9x_1 &+& x_2 &+& x_3 &=& 1\\
2x_1 &+& 10x_2 &+& 3x_3 &=& 2\\
3x_1 &+& 4x_2 &+& 11x_3 &=& 3
\end{array}

$$\mathbf{T}_g =
\begin{bmatrix}
0 & -\frac{1}{9}  & -\frac{1}{9}\\
0  & \frac{1}{45} & -\frac{5}{18}\\
0  & \frac{1}{45} & \frac{13}{99}\\
\end{bmatrix}
$$

In [10]:
max(abs(la.eigvals(Tg)))

0.09534625892455925

## Condição suficiente

Lembre-se que $\rho(\mathbf{A}) \le \|\mathbf{A}\|$, onde $\|\cdot\|$ e uma norma induzida.
Isso nos leva ao seguinte resultado.

**Corolário**. Se um método iterativo possui a forma

$$
\mathbf{x}^{(k+1)} = \mathbf{M} \mathbf{x}^{(k)} + \mathbf{c} \qquad k = 0, 1, \dotsc
$$

e $\|M\| < 1$, para qualquer norma induzida, então ele converge para qualquer valor inicial $\mathbf{x}^{(0)}$.

In [11]:
la.norm(Tj, np.inf), la.norm(Tg, np.inf)

(0.6363636363636364, 0.30000000000000004)

## Matriz com diagonal dominante

Uma matriz $\mathbf{A}$ possui **diagonal estritamente dominante (por linha)** quando

$$
|a_{ii}| > \sum_{\substack{j=1\\ j \ne i}}^n |a_{ij}| \qquad i = 1, 2, \dotsc, n
$$

### Exemplo

\begin{array}{rcrcrcr}
9x_1 &+& x_2 &+& x_3 &=& 1\\
2x_1 &+& 10x_2 &+& 3x_3 &=& 2\\
3x_1 &+& 4x_2 &+& 11x_3 &=& 3
\end{array}

### Exemplo

\begin{array}{rcrcrcr}
x_1 &+& 4x_2 &+& x_3 &=& 1\\
-6x_1 &+& 2x_2 &+& x_3 &=& 2\\
-x_1 &-& x_2 &+& 3x_3 &=& 3
\end{array}

### Critério de convergência alternativo

**Proposição**. Se $\mathbf{A}$ possui diagonal estritamente dominante, então os métodos de Jacobi e Gauss-Seidel convergem para qualquer escolha de $\mathbf{x}^{(0)}$.

## Velocidade de convergência

A velocidade de convergência de um método iterativo depende do raio espectral da matriz do método. Embora não tenhamos um resultado para sistemas em geral, em alguns casos é possível prever qual deles convergirá mais rápido.

## Velocidade de convergência

\begin{array}{rcrcrcr}
9x_1 &+& x_2 &+& x_3 &=& 1\\
2x_1 &+& 10x_2 &+& 3x_3 &=& 2\\
3x_1 &+& 4x_2 &+& 11x_3 &=& 3
\end{array}

In [12]:
abs(la.eigvals(Tj)).max()

0.4472271510919682

In [13]:
abs(la.eigvals(Tg)).max()

0.09534625892455925

## Velocidade de convergência

\begin{array}{rcrcrcr}
7x_1 &+& 6x_2 &+& 9x_3 &=& 2\\
4x_1 &+& 5x_2 &-& 4x_3 &=& 1\\
-7x_1 &-& 3x_2 &+& 8x_3 &=& 3
\end{array}

In [14]:
A = np.array([[ 7.0, 6.0, 9.0],
              [ 4.0, 5.0,-4.0],
              [-7.0,-3.0, 8.0]])
D = np.diag(np.diag(A))
L = np.tril(A,-1)
U = np.triu(A,1)
Tj = -np.dot(la.inv(D),(L+U))
Tg = -np.dot(la.inv(D+L),U)

In [15]:
abs(la.eigvals(Tj)).max()

0.641132809955697

In [16]:
abs(la.eigvals(Tg)).max()

0.7745966692414834

## Velocidade de convergência: caso particular

**Proposição**. Seja $\mathbf{A} = \left[a_{ij}\right]$ uma matriz quadrada de ordem $n$ tal que:
* $a_{ij} \le 0$, para $i \ne j$, e;
* $a_{ii} > 0$.

Então, somente uma das afirmações a seguir é válida:

1. $0 \le \rho\!\left(\mathbf{T}_g\right) < \rho\!\left(\mathbf{T}_j\right) < 1$
2. $1 < \rho\!\left(\mathbf{T}_j\right) < \rho\!\left(\mathbf{T}_g\right)$
3. $\rho\!\left(\mathbf{T}_j\right) = \rho\!\left(\mathbf{T}_g\right) = 0$
4. $\rho\!\left(\mathbf{T}_j\right) = \rho\!\left(\mathbf{T}_g\right) = 1$

## Saiba mais

* Estas anotações foram baseadas na Seção 7.3 de nosso livro-texto: Burden, R. L.; Faires, D.; Burden, A. M., **Análise Numérica**, 3ª ed., Cengage Learning: São Paulo, 2015.

* Se houver tempo, assista aos vídeos da professora Emanuele da UFC [aqui](https://www.youtube.com/playlist?list=PLomBG50UAP0m9ukqkap2GqlPXOBUq8FaL). O material dela é excelente!

* Para aprender sobre a notação assintótica utilizada na representação da quantidade de flops ("Oh-zão" ou Oh-grande), recomendo assistir [este vídeo](https://www.youtube.com/watch?v=gjw7AaOs9P8) da professora Carla (UFABC) ou ler [este material](https://www.ime.usp.br/~pf/analise_de_algoritmos/aulas/Oh.html) do professor Paulo Feofiloff (IME/USP).

Vicente Helano  
UFCA | Centro de Ciências e Tecnologia